# Generated by Django 3.1.7 on 2021-04-27 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Conditional_Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_conditional_event_risk_level', models.CharField(max_length=50)),
                ('total_event_correlation_risk_level', models.CharField(max_length=50)),
                ('total_new_competition_risk_level', models.CharField(max_length=50)),
                ('total_new_opportunity_risk_level', models.CharField(max_length=50)),
                ('last_updated', models.CharField(max_length=50)),
                ('business_basic_info_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.business_basic_info')),
            ],
        ),
        migrations.CreateModel(
            name='Business_Structural_Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_transformation_risk_level', models.CharField(max_length=50)),
                ('seasonality_risk_level', models.CharField(max_length=50)),
                ('new_vs_old_economy', models.CharField(max_length=50)),
                ('geopolitical_risk_level', models.CharField(max_length=50)),
                ('policy_risk_level', models.CharField(max_length=50)),
                ('product_competitiveness_risk_level', models.CharField(max_length=50)),
                ('business_DNA_risk_level', models.CharField(max_length=50)),
                ('contrarian_level', models.CharField(max_length=50)),
                ('overproduction_risk_level', models.CharField(max_length=50)),
                ('last_updated', models.CharField(max_length=50)),
                ('business_basic_info_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.business_basic_info')),
            ],
        ),
        migrations.CreateModel(
            name='Business_Systemic_Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broader_index_risk_level', models.CharField(max_length=50)),
                ('sector_index_risk_level', models.CharField(max_length=50)),
                ('broader_index_correlation_level', models.CharField(max_length=50)),
                ('sector_index_correlation_level', models.CharField(max_length=50)),
                ('contrarian_level', models.CharField(max_length=50)),
                ('macro_risk_level', models.CharField(max_length=50)),
                ('sector_rotation_risk_level', models.CharField(max_length=50)),
                ('last_updated', models.CharField(max_length=50)),
                ('business_basic_info_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business_basic_info')),
            ],
        ),
        migrations.CreateModel(
            name='Risk_Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_weight_coefficient', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hedgeability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_clarity_level', models.CharField(max_length=50)),
                ('risk_quantifiability_level', models.CharField(max_length=50)),
                ('free_cash_liquidity', models.CharField(max_length=50)),
                ('risk_hedge_correlation_clarity_level', models.CharField(max_length=50)),
                ('risk_hedge_correlation_quantifiability_level', models.CharField(max_length=50)),
                ('overall_hedgeability_level', models.CharField(max_length=50)),
                ('business_condition_id', models.ManyToManyField(to='business.Business_Condition')),
                ('business_conditional_risk_id', models.ManyToManyField(to='financial_risk.Business_Conditional_Risk')),
                ('business_finance_id', models.ManyToManyField(to='business.Business_Finance')),
                ('business_preference_id', models.ManyToManyField(to='business.Business_Preference')),
                ('business_structural_risk_id', models.ManyToManyField(to='financial_risk.Business_Structural_Risk')),
                ('business_systemic_risk_id', models.ManyToManyField(to='financial_risk.Business_Systemic_Risk')),
            ],
        ),
        migrations.AddField(
            model_name='business_systemic_risk',
            name='risk_weight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_risk.risk_weight'),
        ),
        migrations.AddField(
            model_name='business_structural_risk',
            name='risk_weight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_risk.risk_weight'),
        ),
        migrations.AddField(
            model_name='business_conditional_risk',
            name='risk_weight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_risk.risk_weight'),
        ),
    ]
