# Generated by Django 3.1.7 on 2021-04-27 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_Level',
            fields=[
                ('uniqueid', models.IntegerField(primary_key=True, serialize=False)),
                ('row1', models.IntegerField()),
                ('row2', models.IntegerField()),
                ('row3', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Auth_Level',
            },
        ),
        migrations.CreateModel(
            name='Client_Entity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('authorization_type_code', models.CharField(max_length=32)),
                ('authorization_entity', models.CharField(max_length=32)),
                ('client_status_type_code', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Client_Entity',
            },
        ),
        migrations.CreateModel(
            name='Data_Set_Task_Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Data_Set_Task_Entity',
            },
        ),
        migrations.CreateModel(
            name='Org_Detail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Org_Detail',
            },
        ),
        migrations.CreateModel(
            name='Org_Entity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Org_Entity',
            },
        ),
        migrations.CreateModel(
            name='User_Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'User_Event',
            },
        ),
        migrations.CreateModel(
            name='User_Entity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('zip_code', models.CharField(max_length=32)),
                ('password_hash', models.CharField(max_length=32)),
                ('user_status_type_code', models.IntegerField()),
                ('client_entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.client_entity')),
                ('org_entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.org_entity')),
            ],
            options={
                'verbose_name_plural': 'User_Entity',
            },
        ),
        migrations.CreateModel(
            name='Task_Entity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('native_id', models.IntegerField()),
                ('status', models.CharField(max_length=32)),
                ('user_event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.user_event')),
            ],
            options={
                'verbose_name_plural': 'Task_Entity',
            },
        ),
        migrations.CreateModel(
            name='Client_Profile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('industry', models.CharField(max_length=32)),
                ('sector', models.CharField(max_length=32)),
                ('annual_revenue', models.FloatField()),
                ('annual_profit', models.FloatField()),
                ('number_of_staff', models.IntegerField()),
                ('client_entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.client_entity')),
                ('org_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.org_detail')),
            ],
            options={
                'verbose_name_plural': 'Client_Profile',
            },
        ),
        migrations.AddField(
            model_name='client_entity',
            name='org_entity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.org_entity'),
        ),
    ]
