# Generated by Django 3.1.7 on 2021-04-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nasdaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=200)),
                ('company_security_name', models.CharField(max_length=200)),
            ],
        ),
    ]
